# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "061086311b26cc09dce60af3f171875e"
name = "testApp"
handle = "testapp-4293"
application_url = "https://zimbabwe-wishlist-black-pattern.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-app-aldo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping,write_customers,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://zimbabwe-wishlist-black-pattern.trycloudflare.com/auth/callback",
  "https://zimbabwe-wishlist-black-pattern.trycloudflare.com/auth/shopify/callback",
  "https://zimbabwe-wishlist-black-pattern.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://zimbabwe-wishlist-black-pattern.trycloudflare.com/prapi"
subpath = "api-bbva"
prefix = "apps"

[pos]
embedded = false
